CREATE OR REPLACE PACKAGE DM_SQL_RPT AS

/*
### Editor: PYZ
### Change Time : 2024-12-30
### Version: 1.0
*/

--获取所有
PROCEDURE GET_ALL_INFO(EXEC_ID IN BIGINT);

--获取SQL涉及表信息
PROCEDURE GET_TAB_INFO(EXEC_ID IN BIGINT);

--获取表涉及索引
PROCEDURE GET_IDX_INFO(EXEC_ID IN BIGINT);

--获取SQL涉及表的统计信息
PROCEDURE GET_STAT_INFO(EXEC_ID IN BIGINT);

--获取SQL执行计划
PROCEDURE GET_SQL_PLAN(EXEC_ID IN BIGINT);

--获取et信息
PROCEDURE GET_SQLET_INFO(EXEC_ID IN BIGINT);

--获取SQL缓存的执行计划
PROCEDURE GET_SQLPLN_CACHE(EXEC_ID IN BIGINT);

--打印历史执行计划  sysplanhist 待定

END DM_SQL_RPT;
/

CREATE OR REPLACE PACKAGE BODY DM_SQL_RPT WITH ENCRYPTION AS 

--获取SQL涉及表信息
PROCEDURE GET_TAB_INFO(EXEC_ID IN BIGINT) AS

SQL_EXEC_ID BIGINT := EXEC_ID;
NTID VARCHAR2(256);
TID VARCHAR2(256);
TB_OWNER VARCHAR2(256);
TB_NAME VARCHAR2(256);

TYPE OBJ_TB IS RECORD(OWNER VARCHAR2(128),TBNAME VARCHAR2(128),NUMROWS VARCHAR2(128),LASTSTAT VARCHAR2(128),PARTED VARCHAR2(3),TMP VARCHAR2(3));
TB_INFO OBJ_TB;

CURSOR CUR_TAB(NTID VARCHAR2) 
    IS SELECT CAST(REGEXP_SUBSTR(NTID,'[^ ]+',1,LEVEL,'i') AS NUMBER)
         FROM DUAL 
      CONNECT BY LEVEL <= LENGTH(NTID) - LENGTH(REGEXP_REPLACE(NTID,' ',''))+1;

CURSOR CUR_COL(TB_OWNER VARCHAR2,TB_NAME VARCHAR2)
    IS SELECT C.COLID+1 AS COLID,C.NAME,C.TYPE$||'('||C.LENGTH$||','||C.SCALE||')' AS COL_TYPE,C.NULLABLE$,C.DEFVAL
         FROM SYSOBJECTS O,
              SYSCOLUMNS C
        WHERE O.ID = C.ID
          AND SF_GET_SCHEMA_NAME_BY_ID(O.SCHID) = TB_OWNER
          AND O.NAME = TB_NAME
          AND O.SUBTYPE$ = 'UTAB'
        ORDER BY C.COLID;

TB_COL CUR_COL%ROWTYPE;

CURSOR CUR_PART_COL(TB_OWNER VARCHAR2,TB_NAME VARCHAR2)
    IS SELECT A.PARTITION_POSITION,A.PARTITION_NAME,B.COLUMN_NAME,A.COMPOSITE,A.SUBPARTITION_COUNT,A.HIGH_VALUE,TO_CHAR(A.NUM_ROWS) AS NUM_ROWS,TO_CHAR(A.LAST_ANALYZED,'YYYY-MM-DD HH24:MI:SS') AS LAST_ANALYZED 
         FROM
        (
         SELECT
                ALLTAB.SCH_NAME TABLE_OWNER,
                ALLTAB.TAB_NAME TABLE_NAME,
                CASE WHEN ALLTAB.SUBPART_COUNT IS NULL THEN 'NO' ELSE 'YES' END COMPOSITE,
                CASE WHEN T_HTABINFO.PARTITION_NAME IS NULL THEN ALLTAB.SUBTAB_NAME ELSE T_HTABINFO.PARTITION_NAME END PARTITION_NAME,
                CASE WHEN ALLTAB.SUBPART_COUNT IS NULL THEN 0 ELSE ALLTAB.SUBPART_COUNT END SUBPARTITION_COUNT,
                SF_GET_PART_HIGH_VALUE(ALLTAB.TAB_ID, ALLTAB.SUBTAB_ID) HIGH_VALUE,
                SF_GET_PART_SEQNO(ALLTAB.TAB_ID, ALLTAB.SUBTAB_ID) PARTITION_POSITION,
                T_SAMP.T_TOTAL NUM_ROWS,
                CAST(T_SAMP.LAST_GATHERED AS DATE) LAST_ANALYZED
          FROM
             (
              SELECT /*+VIEW_PULLUP_FLAG(0)*/
                    TAB.T_TAB_NAME TAB_NAME,
                    TAB.T_TAB_ID TAB_ID,
                    TAB.T_TAB_SCHID TAB_SCHID,
                    TAB.T_SUBTAB_NAME SUBTAB_NAME,
                    TAB.T_SUBTAB_ID SUBTAB_ID,
                    TAB.T_SUBTAB_PID SUBTAB_PID,
                    T_SCH.SCH_NAME SCH_NAME,
                    T_SUBSUBTAB.SUBPART_COUNT SUBPART_COUNT
               FROM
                  (
                    SELECT * FROM (
                      (SELECT NAME T_TAB_NAME, ID T_TAB_ID, SCHID T_TAB_SCHID FROM SYSOBJECTS WHERE TYPE$ = 'SCHOBJ' AND SUBTYPE$ = 'UTAB' AND PID = -1) T_TAB
                         JOIN 
                      (SELECT NAME T_SUBTAB_NAME, ID T_SUBTAB_ID, PID T_SUBTAB_PID FROM SYSOBJECTS WHERE TYPE$ = 'SCHOBJ' AND SUBTYPE$ = 'UTAB' AND PID != -1 AND INFO3&0X3F != 0) T_SUBTAB 
                           ON T_SUBTAB.T_SUBTAB_PID = T_TAB.T_TAB_ID)
                  ) TAB
                LEFT JOIN (SELECT ID SCH_ID, PID SCH_PID, NAME SCH_NAME FROM SYSOBJECTS WHERE TYPE$ = 'SCH') T_SCH ON T_SCH.SCH_ID = TAB.T_TAB_SCHID
                LEFT JOIN (SELECT PID, COUNT(PID) SUBPART_COUNT FROM SYSOBJECTS WHERE SUBTYPE$ = 'UTAB' AND PID != -1 AND INFO3&0X3F != 0 GROUP BY PID) T_SUBSUBTAB ON  T_SUBSUBTAB.PID = TAB.T_SUBTAB_ID
              ) ALLTAB
              LEFT JOIN (SELECT PART_TABLE_ID, PARTITION_NAME FROM SYSHPARTTABLEINFO) T_HTABINFO ON ALLTAB.SUBTAB_ID = T_HTABINFO.PART_TABLE_ID
              LEFT JOIN (SELECT AA.ID, AA.PID, BB.GROUPID FROM SYSOBJECTS AA,  SYSINDEXES BB WHERE AA.ID=BB.ID AND BB.XTYPE&0X01=0) T_INDEX ON T_INDEX.PID = ALLTAB.SUBTAB_ID
              LEFT JOIN (SELECT ID, T_TOTAL, LAST_GATHERED FROM SYSSTATS WHERE COLID = -1) T_SAMP ON (T_SAMP.ID = ALLTAB.SUBTAB_ID)
              ) A,
             (WITH V0 AS
                (SELECT ID, BIN_VALUE, CAST(CAST(SUBSTR(BIN_VALUE, 3,2) || SUBSTR(BIN_VALUE, 1,2) AS VARBINARY) AS INT) AS PART_COL_CNT
                   FROM SYSOBJINFOS
                  WHERE TYPE$ = 'TABPART'
                ),
                 V1 AS
                (SELECT ID,CASE WHEN PART_COL_CNT > 0 THEN CAST(CAST(SUBSTR(BIN_VALUE, 7,2) || SUBSTR(BIN_VALUE, 5,2) AS VARBINARY) AS INT) ELSE NULL END AS COLID,1 AS SEQ FROM V0
                  UNION ALL
                 SELECT ID,CASE WHEN PART_COL_CNT > 1 THEN CAST(CAST(SUBSTR(BIN_VALUE, 15,2) || SUBSTR(BIN_VALUE, 13,2) AS VARBINARY) AS INT) ELSE NULL END AS COLID,2 AS SEQ FROM V0
                  UNION ALL
                 SELECT ID,CASE WHEN PART_COL_CNT > 2 THEN CAST(CAST(SUBSTR(BIN_VALUE, 23,2) || SUBSTR(BIN_VALUE, 21,2) AS VARBINARY) AS INT) ELSE NULL END AS COLID,3 AS SEQ FROM V0
                  UNION ALL
                 SELECT ID,CASE WHEN PART_COL_CNT > 3 THEN CAST(CAST(SUBSTR(BIN_VALUE, 31,2) || SUBSTR(BIN_VALUE, 29,2) AS VARBINARY) AS INT) ELSE NULL END AS COLID,4 AS SEQ FROM V0
                  UNION ALL
                 SELECT ID,CASE WHEN PART_COL_CNT > 4 THEN CAST(CAST(SUBSTR(BIN_VALUE, 39,2) || SUBSTR(BIN_VALUE, 37,2) AS VARBINARY) AS INT) ELSE NULL END AS COLID,5 AS SEQ FROM V0
                )
            SELECT /*+ NLS_SORT_TYPE(0) */
                  B.NAME  AS OWNER,
                  A.NAME  AS NAME,
                  LISTAGG(C.NAME,',') WITHIN GROUP (ORDER BY V1.SEQ) AS COLUMN_NAME
              FROM V1,
                   SYSOBJECTS A,
                   SYSOBJECTS B,
                   SYSCOLUMNS C
             WHERE V1.COLID IS NOT NULL
               AND  A.ID = V1.ID
               AND  C.ID = V1.ID
               AND  C.COLID = V1.COLID
               AND  B.ID = A.SCHID
             GROUP BY  B.NAME,A.NAME
              ) B
         WHERE A.TABLE_OWNER = B.OWNER
           AND A.TABLE_NAME = B.NAME
           AND A.TABLE_OWNER = TB_OWNER
           AND A.TABLE_NAME = TB_NAME
         ORDER BY A.PARTITION_POSITION ASC;

TAB_PART_COL CUR_PART_COL%ROWTYPE;

BEGIN

--get table id
SELECT SP.TABLEID INTO NTID
  FROM V$SQL_HISTORY SH,
       V$SQL_PLAN SP
 WHERE SH.SQL_ID = SP.SQL_ID
   AND SH.EXEC_ID= SQL_EXEC_ID;

OPEN CUR_TAB(NTID);
LOOP
FETCH CUR_TAB INTO TID;
EXIT WHEN CUR_TAB%NOTFOUND;

--get table owner & name
SELECT SF_GET_SCHEMA_NAME_BY_ID(SCHID) AS OWNER,NAME INTO TB_OWNER,TB_NAME FROM SYSOBJECTS WHERE ID = TID;

SELECT /*+ COMPLEX_VIEW_MERGING(0) */
        O2.NAME OWNER,
        O3.NAME TABLE_NAME,
        TO_CHAR(SAMP.T_TOTAL) NUM_ROWS,
        TO_CHAR(SAMP.LAST_GATHERED,'YYYY-MM-DD HH24:MI:SS') LAST_ANALYZED,
        CASE WHEN SUB_COUNT IS NOT NULL AND SUB_COUNT > 0 THEN 'YES' ELSE 'NO' END PARTITIONED,
        CASE WHEN O3.INFO3_TMP IS NOT NULL AND O3.INFO3_TMP THEN 'Y' ELSE 'N' END TEMPORARY
	    INTO TB_INFO
     FROM
		  (SELECT ID, NAME, PID FROM SYSOBJECTS WHERE TYPE$ = 'SCH') O2
     JOIN (SELECT ID, NAME, PID, SCHID, INFO1, INFO3, INFO3 & 0XC0 INFO3_TMP, VALID, SUB_COUNT FROM
		  (WITH T_TAB AS (SELECT * FROM SYSOBJECTS WHERE TYPE$ = 'SCHOBJ' AND SUBTYPE$ IN ('UTAB', 'STAB') AND NAME NOT LIKE '_%$AUX' AND NAME NOT LIKE '_%$RAUX' AND NAME NOT LIKE '_%$DAUX' AND NAME NOT LIKE '_%$UAUX' AND NAME NOT LIKE '_%$ALOG' AND INFO3 & 0x100000000 = 0) --排除内部表
		   SELECT * FROM (SELECT * FROM T_TAB WHERE PID = -1) P_TAB
		   LEFT JOIN
		  (SELECT PID SUB_PID, COUNT(PID) SUB_COUNT FROM T_TAB WHERE PID IS NOT NULL AND PID > 0 GROUP BY PID) SUBTAB
		   ON SUBTAB.SUB_PID =  P_TAB.ID)
		  ) O3
	   ON O3.SCHID = O2.ID
	 LEFT JOIN (SELECT ID, T_TOTAL, LAST_GATHERED FROM SYSSTATS WHERE COLID=-1) SAMP ON O3.ID = SAMP.ID
    WHERE O2.NAME = TB_OWNER
      AND O3.NAME = TB_NAME;

--print table global info
PRINT(REPEAT('#',81));
PRINT '##### TABLE INFO : '||TB_OWNER||'.'||TB_NAME;
PRINT(REPEAT('-',81));
PRINT('|'||LPAD('OWNER',10,' ')||'|'||LPAD('TABLE_NAME',13,' ')||'|'||LPAD('NUM_ROWS',9,' ')||'|'||LPAD('LAST_ANALYZED',20,' ')||'|'||LPAD('PARTITIONED',12,' ')||'|'||LPAD('TEMPORARY',10,' ')||'|');
PRINT(REPEAT('-',81));
PRINT('|'||LPAD(TB_INFO.OWNER,10,' ')||'|'||LPAD(TB_INFO.TBNAME,13,' ')||'|'||LPAD(NVL(TB_INFO.NUMROWS,'NULL'),9,' ')||'|'||LPAD(NVL(TB_INFO.LASTSTAT,'NULL'),20,' ')||'|'||LPAD(TB_INFO.PARTED,12,' ')||'|'||LPAD(TB_INFO.TMP,10,' ')||'|');
PRINT(REPEAT('-',81));

--print table partition info one level
      IF TB_INFO.PARTED = 'YES' THEN
         OPEN CUR_PART_COL(TB_OWNER,TB_NAME);
         PRINT '##### TABLE PART INFO : '||TB_OWNER||'.'||TB_NAME;
         PRINT(REPEAT('-',96));
         PRINT('|'||LPAD('PART_POSI',9,' ')||'|'||LPAD('PART_NAME',13,' ')||'|'||LPAD('COLUMN_NAME',13,' ')||'|'||LPAD('SUBPART_CNT',11,' ')||'|'||LPAD('HIGH_VALUE',12,' ')||'|'||LPAD('NUM_ROWS',10,' ')||'|'||LPAD('LAST_ANALYZED',20,' ')||'|');
         PRINT(REPEAT('-',96));
         LOOP
         FETCH CUR_PART_COL INTO TAB_PART_COL;
         EXIT WHEN CUR_PART_COL%NOTFOUND;
         PRINT('|'||LPAD(TAB_PART_COL.PARTITION_POSITION,9,' ')||'|'||
                    LPAD(TAB_PART_COL.PARTITION_NAME,13,' ')||'|'||
                    LPAD(TAB_PART_COL.COLUMN_NAME,13,' ')||'|'||
                    LPAD(TAB_PART_COL.SUBPARTITION_COUNT,11,' ')||'|'||
                    LPAD(TAB_PART_COL.HIGH_VALUE,12,' ')||'|'||
                    LPAD(NVL(TAB_PART_COL.NUM_ROWS,'NULL'),10,' ')||'|'||
                    LPAD(NVL(TAB_PART_COL.LAST_ANALYZED,'NULL'),20,' ')||'|');
         END LOOP;
         PRINT(REPEAT('-',96));
         CLOSE CUR_PART_COL;
        
      END IF;

--print table column info
PRINT '##### COLUMN INFO : '||TB_OWNER||'.'||TB_NAME;
PRINT(REPEAT('-',81));
PRINT('|'||LPAD('COLUMN_ID',10,' ')||'|'||LPAD('COLUMN_NAME',20,' ')||'|'||LPAD('COLUMN_TYPE',20,' ')||'|'||LPAD('NULLABLE',10,' ')||'|'||LPAD('DEFAULT_VAL',15,' ')||'|');
PRINT(REPEAT('-',81));
OPEN CUR_COL(TB_OWNER,TB_NAME);
LOOP
FETCH CUR_COL INTO TB_COL;
EXIT WHEN CUR_COL%NOTFOUND;
PRINT('|'||LPAD(TB_COL.COLID,10,' ')||'|'||LPAD(TB_COL.NAME,20,' ')||'|'||LPAD(TB_COL.COL_TYPE,20,' ')||'|'||LPAD(TB_COL.NULLABLE$,10,' ')||'|'||LPAD(NVL(TB_COL.DEFVAL,'NULL'),15,' ')||'|');
END LOOP;
CLOSE CUR_COL;
END LOOP;
PRINT(REPEAT('-',81));
CLOSE CUR_TAB;

EXCEPTION WHEN OTHERS THEN PRINT(SQLCODE||':'||SQLERRM);

END GET_TAB_INFO;

--获取表涉及索引
PROCEDURE GET_IDX_INFO(EXEC_ID IN BIGINT) AS

SQL_EXEC_ID BIGINT := EXEC_ID;  --输入exec_id
NTID VARCHAR2(256);
TID VARCHAR2(256);
TB_OWNER VARCHAR2(256);
TB_NAME VARCHAR2(256);

CURSOR CUR_TAB(NTID VARCHAR2) 
    IS SELECT CAST(REGEXP_SUBSTR(NTID,'[^ ]+',1,LEVEL,'i') AS NUMBER)
         FROM DUAL 
      CONNECT BY LEVEL <= LENGTH(NTID) - LENGTH(REGEXP_REPLACE(NTID,' ',''))+1;

CURSOR CUR_IDX_DDL(TB_OWNER VARCHAR2,TB_NAME VARCHAR2)
    IS SELECT I.ID
         FROM SYSOBJECTS I,SYSOBJECTS T,SYSINDEXES IDX
        WHERE I.PID = T.ID
          AND I.ID = IDX.ID
          AND SF_GET_SCHEMA_NAME_BY_ID(T.SCHID) = TB_OWNER
          AND T.NAME = TB_NAME
          AND I.SUBTYPE$ = 'INDEX'
          AND IDX.XTYPE <> 0
        ORDER BY I.NAME;

IDX_ID  BIGINT;
IDX_DDL VARCHAR2(1024);

CURSOR CUR_IDX_COL(TB_OWNER VARCHAR2,TB_NAME VARCHAR2,IDX_ID BIGINT)
    IS SELECT O1.ID,
              O1.NAME INDEX_NAME,
              COL.NAME COLUMN_NAME, 
              CAST (SF_GET_INDEX_KEY_SEQ(I.KEYNUM, I.KEYINFO, COL.COLID) AS NUMBER) COLUMN_POSITION,
              CASE WHEN SF_GET_INDEX_KEY_ORDER(I.KEYNUM,I.KEYINFO,COL.COLID)='A' THEN 'ASC' ELSE 'DESC' END DESCEND,
              I.TYPE$ TYPE,
              CASE I.XTYPE WHEN 0 THEN 'CLUSTER' WHEN 1 THEN 'SEC' WHEN 2 THEN 'FUNC' ELSE I.XTYPE END XTYPE,
              CASE I.FLAG WHEN 1 THEN 'SYS' WHEN 2 THEN 'VIRT' WHEN 4 THEN 'PK' WHEN 8 THEN 'TMP' WHEN 16 THEN 'INVA' WHEN 32 THEN 'FPOOL' ELSE I.FLAG END FLAG
         FROM SYS.SYSOBJECTS O1 LEFT JOIN SYS.SYSINDEXES I ON O1.ID = I.ID,
              SYS.SYSOBJECTS O2 LEFT JOIN SYS.SYSCOLUMNS COL ON O2.ID = COL.ID,
              SYS.SYSOBJECTS O3
        WHERE O2.ID = O1.PID AND O3.ID = O2.SCHID AND SF_COL_IS_IDX_KEY(I.KEYNUM, I.KEYINFO, COL.COLID) = 1
          AND SF_GET_SCHEMA_NAME_BY_ID(O2.SCHID) = TB_OWNER
          AND O2.NAME = TB_NAME
          AND O1.ID = IDX_ID
          ORDER BY 4;

IDX_COL CUR_IDX_COL%ROWTYPE;

BEGIN
--GET TABLE ID
SELECT SP.TABLEID INTO NTID
  FROM V$SQL_HISTORY SH,
       V$SQL_PLAN SP
 WHERE SH.SQL_ID = SP.SQL_ID
   AND SH.EXEC_ID= SQL_EXEC_ID;

--LOOP LEVEL 1, GET TABLE OWNER & NAME
OPEN CUR_TAB(NTID);
LOOP
FETCH CUR_TAB INTO TID;
EXIT WHEN CUR_TAB%NOTFOUND;

SELECT SF_GET_SCHEMA_NAME_BY_ID(SCHID) AS OWNER,NAME INTO TB_OWNER,TB_NAME FROM SYSOBJECTS WHERE ID = TID;

PRINT(REPEAT('#',100));
PRINT '##### INDEX INFO : '||TB_OWNER||'.'||TB_NAME;

--LOOP LEVEL 2, GET INDEX DDL
OPEN CUR_IDX_DDL(TB_OWNER,TB_NAME);
LOOP
FETCH CUR_IDX_DDL INTO IDX_ID;
EXIT WHEN CUR_IDX_DDL%NOTFOUND;
EXECUTE IMMEDIATE 'SELECT INDEXDEF('||IDX_ID||',1)' INTO IDX_DDL;
PRINT(IDX_DDL);

--LOOP LEVEL 3, GET INDEX COL
OPEN CUR_IDX_COL(TB_OWNER,TB_NAME,IDX_ID);
PRINT(REPEAT('-',100));
PRINT('|'||LPAD('ID',10,' ')||'|'||LPAD('INDEX_NAME',20,' ')||'|'||LPAD('COLUMN_NAME',20,' ')||'|'||LPAD('COLUMN_POSITION',16,' ')||'|'||LPAD('DESCEND',9,' ')||'|'||LPAD('TYPE',5,' ')||'|'||LPAD('XTYPE',6,' ')||'|'||LPAD('FLAG',5,' ')||'|');
PRINT(REPEAT('-',100));
LOOP
FETCH CUR_IDX_COL INTO IDX_COL;
EXIT WHEN CUR_IDX_COL%NOTFOUND;
PRINT('|'||LPAD(IDX_COL.ID,10,' ')||'|'||LPAD(IDX_COL.INDEX_NAME,20,' ')||'|'||LPAD(IDX_COL.COLUMN_NAME,20,' ')||'|'||LPAD(IDX_COL.COLUMN_POSITION,16,' ')||'|'||LPAD(IDX_COL.DESCEND,9,' ')||'|'||LPAD(IDX_COL.TYPE,5,' ')||'|'||LPAD(IDX_COL.XTYPE,6,' ')||'|'||LPAD(IDX_COL.FLAG,5,' ')||'|');
END LOOP;
PRINT(REPEAT('-',100));
CLOSE CUR_IDX_COL;

END LOOP;
CLOSE CUR_IDX_DDL;

END LOOP;
CLOSE CUR_TAB;

EXCEPTION WHEN OTHERS THEN 
PRINT SQLCODE||' '||SQLERRM;

END GET_IDX_INFO;

--获取sql涉及表的统计信息
PROCEDURE GET_STAT_INFO(EXEC_ID IN BIGINT) AS

SQL_EXEC_ID BIGINT := EXEC_ID;
NTID VARCHAR2(256);
TID VARCHAR2(256);
TB_OWNER VARCHAR2(256);
TB_NAME VARCHAR2(256);
IS_STATS INT;

CURSOR CUR_TAB(NTID VARCHAR2) 
    IS SELECT CAST(REGEXP_SUBSTR(NTID,'[^ ]+',1,LEVEL,'i') AS NUMBER)
         FROM DUAL 
      CONNECT BY LEVEL <= LENGTH(NTID) - LENGTH(REGEXP_REPLACE(NTID,' ',''))+1;

CURSOR CUR_STAT(TB_OWNER VARCHAR2,TB_NAME VARCHAR2)
    IS SELECT *
         FROM (
         SELECT C.NAME AS COL_NAME,C.COLID+1 AS COL_ID,C.TYPE$ AS COL_TYPE,S.T_TOTAL,S.N_SMAPLE,S.N_DISTINCT,S.N_NULL,S.N_BUCKETS,TO_CHAR(S.LAST_GATHERED,'YYYY-MM-DD HH24:MI:SS') AS LAST_GATHERED
           FROM SYSSTATS S 
          INNER JOIN SYSOBJECTS O ON S.ID = O.ID
          INNER JOIN SYSCOLUMNS C ON O.ID = C.ID AND S.COLID = C.COLID 
          WHERE SF_GET_SCHEMA_NAME_BY_ID(O.SCHID) = TB_OWNER
            AND O.NAME= TB_NAME
            AND O.SUBTYPE$='UTAB'
           )
       ORDER BY COL_ID;

V_STAT CUR_STAT%ROWTYPE;

BEGIN

--GET TABLE ID
SELECT SP.TABLEID INTO NTID
  FROM V$SQL_HISTORY SH,
       V$SQL_PLAN SP
 WHERE SH.SQL_ID = SP.SQL_ID
   AND SH.EXEC_ID= SQL_EXEC_ID;

--LOOP LEVEL 1, GET TABLE OWNER & NAME
OPEN CUR_TAB(NTID);
LOOP
FETCH CUR_TAB INTO TID;
EXIT WHEN CUR_TAB%NOTFOUND;

--table id to table name
SELECT SF_GET_SCHEMA_NAME_BY_ID(SCHID) AS OWNER,NAME INTO TB_OWNER,TB_NAME FROM SYSOBJECTS WHERE ID = TID;

SELECT CASE WHEN EXISTS (SELECT 1
                           FROM SYSSTATS S ,
                                SYSOBJECTS O
                          WHERE S.ID = O.ID 
                            AND S.COLID >= 0  -- -1 
                            AND O.SCHID = (SELECT ID FROM SYSOBJECTS WHERE NAME = TB_OWNER AND TYPE$='SCH')
                            AND O.NAME = TB_NAME
                            AND TYPE$ = 'SCHOBJ' 
                            AND O.SUBTYPE$ = 'UTAB'
                         )
            THEN 1 ELSE 0 
        END INTO IS_STATS
  FROM DUAL;

	IF IS_STATS = 1 THEN
		
		PRINT(REPEAT('#',118));
		PRINT '##### TABLE STATS INFO : '||TB_OWNER||'.'||TB_NAME;
		PRINT(REPEAT('-',118));
        PRINT('|'||LPAD('COL_NAME',20,' ')||'|'||
                   LPAD('COL_ID',7,' ')||'|'||
                   LPAD('COL_TYPE',10,' ')||'|'||
                   LPAD('T_TOTAL',10,' ')||'|'||
                   LPAD('N_SMAPLE',10,' ')||'|'||
                   LPAD('N_DISTINCT',11,' ')||'|'||
                   LPAD('N_NULL',10,' ')||'|'||
                   LPAD('N_BUCKETS',10,' ')||'|'||
                   LPAD('LAST_GATHERED',20,' ')||'|'
              );
		PRINT(REPEAT('-',118));
		
		--LOOP LEVEL 2, GET TABLE STAT
		OPEN CUR_STAT(TB_OWNER,TB_NAME);
		LOOP
		FETCH CUR_STAT INTO V_STAT;
		EXIT WHEN CUR_STAT%NOTFOUND;
		PRINT('|'||LPAD(V_STAT.COL_NAME,20,' ')||'|'||
                   LPAD(V_STAT.COL_ID,7,' ')||'|'||
                   LPAD(V_STAT.COL_TYPE,10,' ')||'|'||
                   LPAD(V_STAT.T_TOTAL,10,' ')||'|'||
                   LPAD(V_STAT.N_SMAPLE,10,' ')||'|'||
                   LPAD(V_STAT.N_DISTINCT,11,' ')||'|'||
                   LPAD(V_STAT.N_NULL,10,' ')||'|'||
                   LPAD(V_STAT.N_BUCKETS,10,' ')||'|'||
                   LPAD(V_STAT.LAST_GATHERED,20,' ')||'|'
              );

		END LOOP;
		PRINT(REPEAT('-',118));
		CLOSE CUR_STAT;
	
	ELSE
		
		PRINT '##### TABLE STATS INFO : '||TB_OWNER||'.'||TB_NAME||' STATISTICS IS NULL.';

	END IF;

END LOOP;
CLOSE CUR_TAB;

EXCEPTION WHEN OTHERS THEN 
PRINT SQLCODE||' '||SQLERRM;

END GET_STAT_INFO;

--获取SQL执行计划
PROCEDURE GET_SQL_PLAN(EXEC_ID IN BIGINT) AS

SQL_EXEC_ID BIGINT := EXEC_ID;

CURSOR CUR_SQLPLN(SQL_EXEC_ID BIGINT)
    IS WITH V_SQL_PLAN 
         AS (SELECT SP.SQL_ID,SP.PLN_ADDR
               FROM V$SQL_HISTORY SH,
                    V$SQL_PLAN SP   
              WHERE SH.SQL_ID = SP.SQL_ID
                AND SH.EXEC_ID = SQL_EXEC_ID)
       SELECT ROWNUM AS SEQ,
              SPN.DEPTH,
              CONCAT(REPEAT('  ',(SPN.DEPTH)),'#',SPN.OPERATION,': [',SPN.COST,',',SPN.CARD,',',SPN.BYTES,']; ',
                     CASE WHEN SPN.FILTER != 'NULL' THEN SPN.FILTER||'; ' END,
                     CASE WHEN SPN.OPTIONS != 'NULL' THEN 'SCAN_TYPE('||SPN.OPTIONS||'); ' END,
                     CASE WHEN SPN.INDEX_NAME != 'NULL' THEN SPN.INDEX_NAME END,
                     CASE WHEN SPN.TABLE_NAME != 'NULL' THEN '('||SPN.TABLE_NAME||CASE WHEN SPN.TABLE_ALIAS != 'NULL' THEN ' AS '||SPN.TABLE_ALIAS END ||'); ' END,
                     CASE WHEN SPN.SCAN_RANGE != 'NULL' THEN 'SCAN_RANGE'||SPN.SCAN_RANGE||'; ' END,
                     'CPU_COST:'||nvl(CPU_COST,0)||'; ','IO_COST:'||nvl(IO_COST,0)
                    ) SQL_PLAN
         FROM V$SQL_PLAN_NODE SPN
        WHERE SPN.SQL_ID = (SELECT SQL_ID FROM V_SQL_PLAN)
          AND SPN.PLN_ADDR = (SELECT PLN_ADDR FROM V_SQL_PLAN);

V_SQLPLN CUR_SQLPLN%ROWTYPE;
V_MAXLEN NUMBER;

BEGIN

SELECT MAX(LENGTH(SQL_PLAN)) INTO V_MAXLEN
  FROM (
      WITH V_SQL_PLAN 
        AS (SELECT SP.SQL_ID,SP.PLN_ADDR
        FROM V$SQL_HISTORY SH,
             V$SQL_PLAN SP
       WHERE SH.SQL_ID = SP.SQL_ID
         AND SH.EXEC_ID = SQL_EXEC_ID)
      SELECT
       CONCAT(REPEAT('  ',(SPN.DEPTH)),'#',SPN.OPERATION,': [',SPN.COST,',',SPN.CARD,',',SPN.BYTES,']; ',
              CASE WHEN SPN.FILTER != 'NULL' THEN SPN.FILTER||'; ' END,
              CASE WHEN SPN.OPTIONS != 'NULL' THEN 'SCAN_TYPE('||SPN.OPTIONS||'); ' END,
              CASE WHEN SPN.INDEX_NAME != 'NULL' THEN SPN.INDEX_NAME END,
              CASE WHEN SPN.TABLE_NAME != 'NULL' THEN '('||SPN.TABLE_NAME||CASE WHEN SPN.TABLE_ALIAS != 'NULL' THEN ' AS '||SPN.TABLE_ALIAS END ||'); ' END,
              CASE WHEN SPN.SCAN_RANGE != 'NULL' THEN 'SCAN_RANGE'||SPN.SCAN_RANGE||'; ' END,
              'CPU_COST:'||nvl(CPU_COST,0)||'; ','IO_COST:'||nvl(IO_COST,0)
              ) SQL_PLAN
       FROM V$SQL_PLAN_NODE SPN
      WHERE SPN.SQL_ID = (SELECT SQL_ID FROM V_SQL_PLAN)
        AND SPN.PLN_ADDR = (SELECT PLN_ADDR FROM V_SQL_PLAN) 
);

--LOOP LEVEL 1, GET SQL PLAN
OPEN CUR_SQLPLN(SQL_EXEC_ID);

	PRINT(REPEAT('#',V_MAXLEN+12));
	PRINT '##### SQL PLAN INFO :';
	PRINT(REPEAT('-',V_MAXLEN+12));
    PRINT('|'||LPAD('SEQ',4,' ')||'|'||LPAD('DEP',4,' ')||'|'||RPAD('SQL_PLAN',V_MAXLEN,' ')||'|');
    PRINT(REPEAT('-',V_MAXLEN+12));

LOOP
FETCH CUR_SQLPLN INTO V_SQLPLN;
EXIT WHEN CUR_SQLPLN%NOTFOUND;
		PRINT('|'||LPAD(V_SQLPLN.SEQ,4,' ')||'|'||LPAD(V_SQLPLN.DEPTH,4,' ')||'|'||RPAD(V_SQLPLN.SQL_PLAN,V_MAXLEN,' ')||'|');

END LOOP;
	PRINT(REPEAT('-',V_MAXLEN+12));

CLOSE CUR_SQLPLN;	

EXCEPTION WHEN OTHERS THEN 
PRINT SQLCODE||' '||SQLERRM;

END GET_SQL_PLAN;

--获取et信息
PROCEDURE GET_SQLET_INFO(EXEC_ID IN BIGINT) AS

SQL_EXEC_ID BIGINT := EXEC_ID;
IS_ET INT;

CURSOR CUR_ET(SQL_EXEC_ID BIGINT)
    IS SELECT
             NAME                      AS "OP"      ,
             TRUNC(TIME_USED/1000.0,2) AS "TIME(MS)",
             CAST(TIME_USED * 100.0/SUM(TIME_USED) OVER() AS DEC(10, 2)) || '%' AS "PERCENT",
             RANK() OVER (ORDER BY TIME_USED DESC) AS "RANK"             ,
             SEQ_NO                                AS "SEQ"              ,
             N_ENTER                               AS "N_ENTER"          ,
             MEM_USED                              AS "MEM_USED(KB)"     ,
             DISK_USED                             AS "DISK_USED(KB)"    ,
             HASH_USED_CELLS                       AS "HASH_USED_CELLS"  ,
             HASH_CONFLICT                         AS "HASH_CONFLICT"    --,
             --DHASH3_USED_CELLS                     AS "DHASH3_USED_CELLS",
             --DHASH3_CONFLICT                       AS "DHASH3_CONFLICT"
         FROM V$SQL_NODE_HISTORY A,
              V$SQL_NODE_NAME B
        WHERE A.TYPE$   = B.TYPE$
          AND EXEC_ID   = SQL_EXEC_ID
          AND TIME_USED > 0
        ORDER BY 2;

V_ET CUR_ET%ROWTYPE;

BEGIN

SELECT CASE WHEN EXISTS (SELECT 1 FROM V$SQL_NODE_HISTORY A,V$SQL_NODE_NAME B WHERE A.TYPE$ = B.TYPE$ AND EXEC_ID = SQL_EXEC_ID AND TIME_USED > 0 LIMIT 1)
            THEN 1 ELSE 0
        END INTO IS_ET
  FROM DUAL;
 
IF IS_ET = 1 THEN

--LOOP LEVEL 1, GET ET INFO
OPEN CUR_ET(SQL_EXEC_ID);

	PRINT(REPEAT('#',100));
	PRINT '##### SQL ET INFO :';
	PRINT(REPEAT('-',100));
    PRINT('|'||LPAD('OP',7,' ')||'|'||
               LPAD('TIME(MS)',11,' ')||'|'||
               LPAD('PERCENT',7,' ')||'|'||
               LPAD('RANK',5,' ')||'|'||
               LPAD('SEQ',5,' ')||'|'||
               LPAD('N_ENTER',7,' ')||'|'||
               LPAD('MEM(KB)',11,' ')||'|'||
               LPAD('DISK(KB)',11,' ')||'|'||
               LPAD('HASH_CELLS',11,' ')||'|'||
               LPAD('HASH_CONFLICT',14,' ')||'|'
              );
    PRINT(REPEAT('-',100));

LOOP
FETCH CUR_ET INTO V_ET;
EXIT WHEN CUR_ET%NOTFOUND;

		PRINT('|'||LPAD(V_ET.OP,7,' ')||'|'||
                   LPAD(V_ET."TIME(MS)",11,' ')||'|'||
                   LPAD(V_ET."PERCENT",7,' ')||'|'||
                   LPAD(V_ET.RANK,5,' ')||'|'||
                   LPAD(V_ET.SEQ,5,' ')||'|'||
                   LPAD(V_ET.N_ENTER,7,' ')||'|'||
                   LPAD(V_ET."MEM_USED(KB)",11,' ')||'|'||
                   LPAD(V_ET."DISK_USED(KB)",11,' ')||'|'||
                   LPAD(V_ET.HASH_USED_CELLS,11,' ')||'|'||
                   LPAD(V_ET.HASH_CONFLICT,14,' ')||'|'
              );

END LOOP;
	PRINT(REPEAT('-',100));
CLOSE CUR_ET;	

ELSE		
	PRINT '##### SQL ET INFO IS NULL.';
END IF;

EXCEPTION WHEN OTHERS THEN 
PRINT SQLCODE||' '||SQLERRM;

END GET_SQLET_INFO;

--获取SQL缓存的执行计划
PROCEDURE GET_SQLPLN_CACHE(EXEC_ID IN BIGINT) AS

SQL_EXEC_ID BIGINT := EXEC_ID;

EVENT_CMD VARCHAR2(2000);
CACHE_ITEM_ID BIGINT;
PLNTIME VARCHAR2(20) := TO_CHAR(SYSDATE,'YYYYMMDDHH24MI');
TRACE_PATH VARCHAR2(64);

BEGIN

    SELECT CP.CACHE_ITEM INTO CACHE_ITEM_ID
      FROM V$CACHEPLN CP,
           V$SQL_PLAN SP,
           V$SQL_HISTORY SH
     WHERE SP.HASH_VALUE = CP.HASH_VALUE
       AND SP.SQLCACHE = CP.SQLCACHE
       AND SH.SQL_ID = SP.SQL_ID
       AND SH.EXEC_ID = SQL_EXEC_ID;
    
    SELECT PARA_VALUE INTO TRACE_PATH FROM V$DM_INI WHERE PARA_NAME='TRACE_PATH';
    
    EVENT_CMD := 'ALTER SESSION SET EVENTS ''IMMEDIATE TRACE NAME PLNDUMP LEVEL '||CACHE_ITEM_ID||',DUMP_FILE '''''||TRACE_PATH||'/DM_SQL_PLN_'||PLNTIME||'.trc''''''';

	EXECUTE IMMEDIATE EVENT_CMD;
    --PRINT(EVENT_CMD);

EXCEPTION WHEN OTHERS THEN 
PRINT SQLCODE||' '||SQLERRM;

END GET_SQLPLN_CACHE;

--汇总
PROCEDURE GET_ALL_INFO(EXEC_ID IN BIGINT) AS

SQL_EXEC_ID BIGINT := EXEC_ID;

BEGIN
--获取SQL涉及表信息
	GET_TAB_INFO(SQL_EXEC_ID);

--获取表涉及索引
	GET_IDX_INFO(SQL_EXEC_ID);

--获取SQL涉及表的统计信息
	GET_STAT_INFO(SQL_EXEC_ID);

--获取SQL执行计划
	GET_SQL_PLAN(SQL_EXEC_ID);

--获取et信息
	GET_SQLET_INFO(SQL_EXEC_ID);

--获取SQL缓存的执行计划
	GET_SQLPLN_CACHE(SQL_EXEC_ID);

END GET_ALL_INFO;

END DM_SQL_RPT;
/




/*
call DM_SQL_RPT.GET_ALL_INFO(11410);
call DM_SQL_RPT.GET_TAB_INFO(10303);
call DM_SQL_RPT.GET_IDX_INFO(10303);
call DM_SQL_RPT.GET_STAT_INFO(10303);
call DM_SQL_RPT.GET_SQLET_INFO(11148);

*/


